import React from 'react';
import {inject} from 'mobx-react';
import {observer} from 'mobx-react';
import {Text, Content, Icon} from 'native-base';
import {
  ActivityIndicator,
  StyleSheet,
  View,
  ViewProperties,
  Clipboard,
  TouchableOpacity,
} from 'react-native';
import {logger} from 'react-native-logs';
import DeviceInfo from 'react-native-device-info';
import Permissions from 'react-native-permissions';
import {AppColors, AppFonts} from '../theme';
import {ConexusLightbox} from './base-lightbox';
import {DeviceStore, UserStore} from '../stores';
import _ from 'lodash';
import {getSnapshot} from 'mobx-state-tree';
import PushNotification from 'react-native-push-notification';
import {ActionButton} from '../components';
const log = logger.createLogger();
interface InfoItemProps {
  data: {
    label: string;
    value: string | object;
  }[];
}
const InfoList: React.SFC<InfoItemProps> = ({data}) => {
  const onCopy = (value: string) => {
    log.info('copy', value);
    Clipboard.setString(value);
  };
  const onPushTest = () => {
    PushNotification.localNotification({
      /* Android Only Properties */
      // id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      // ticker: 'My Notification Ticker', // (optional)
      // autoCancel: true, // (optional) default: true
      // largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      // smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      // bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
      // subText: 'This is a subText', // (optional) default: none
      // color: 'red', // (optional) default: system default
      // vibrate: true, // (optional) default: true
      // vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      // tag: 'some_tag', // (optional) add tag to message
      // group: 'group', // (optional) add group to message
      // ongoing: false, // (optional) set whether this is an "ongoing" notification

      /* iOS only properties */
      // alertAction: // (optional) default: view
      // category:  // (optional) default: null
      // userInfo: // (optional) default: null (object containing additional notification data)

      /* iOS and Android properties */
      title: 'My Notification Title', // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
      message: 'My Notification Message', // (required)
      playSound: false, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
      actions: '["Yes", "No"]', // (Android only) See the doc for notification actions to know more
    });
  };
  return (
    <Content>
      <ActionButton primary title="test" onPress={onPushTest} />
      {data.map((item, i) => {
        return (
          <TouchableOpacity
            key={`info-${i}`}
            onPressOut={() =>
              onCopy(
                !_.isObject(item.value)
                  ? (item.value || '').toString()
                  : JSON.stringify(item.value),
              )
            }>
            <View style={{marginTop: i === 0 ? 0 : 10}}>
              <View key={`info-${i}-l`} style={{flexDirection: 'row'}}>
                <Text style={{fontSize: 14}}>{item.label + '  '}</Text>
                <Icon name="ios-copy" style={{marginLeft: 6, fontSize: 14}} />
              </View>
              {!_.isObject(item.value) ? (
                <Text style={{fontSize: 8}} textBreakStrategy="simple">
                  {item.value}
                </Text>
              ) : (
                Object.keys(item.value).map(key => (
                  <Text
                    key={`details-${i}-${key}-l`}
                    style={{fontSize: 8}}
                    textBreakStrategy="simple">{`${key}: ${item.value[key]}`}</Text>
                ))
              )}
            </View>
          </TouchableOpacity>
        );
      })}
    </Content>
  );
};
interface DeviceInfoLightboxProps extends ViewProperties {
  deviceStore?: DeviceStore;
  userStore?: UserStore;
}

interface DeviceInfoLightboxState {
  title?: string;
  loading?: boolean;
  actionText?: string;
  cameraPermission?: boolean;
  photoPermission?: boolean;
  permissions?: any;
}
@inject('deviceStore', 'userStore')
@observer
export class DeviceInfoLightbox extends React.Component<
  DeviceInfoLightboxProps,
  DeviceInfoLightboxState
> {
  componentDidMount() {
    log.info('SCENE', 'Mounted Call');
    // this.props.deviceStore.checkPermissions().then(resp => {
    //   this.setState({permissions: resp});
    // });
  }
  constructor(props, context) {
    super(props, context);

    this.state = {
      loading: false,
      actionText: 'ok',
      // permissions: Permissions.getTypes(),
    };
  }

  render() {
    let {loading, title} = this.state;
    let {userStore} = this.props;
    let {pushToken, authToken, permissions} = this.props.deviceStore;
    let perms = JSON.stringify(getSnapshot(permissions));
    title = 'Device Info';
    let items = [
      {label: 'User', value: userStore.user ? userStore.user.username : ''},
      {label: 'Push Token', value: pushToken},
      {label: 'Device Id', value: DeviceInfo.getUniqueId()},
      {label: 'API Token', value: authToken},
      {label: 'Phone', value: DeviceInfo.getPhoneNumber()},
      {label: 'Permissions', value: perms},
    ];
    return (
      <ConexusLightbox
        closeable
        style={{padding: 0}}
        title={title}
        height={420}
        horizontalPercent={0.9}>
        <View style={styles.content}>
          {!loading && <InfoList data={items} />}
          {loading && (
            <ActivityIndicator color={AppColors.blue} style={{flex: 1}} />
          )}
        </View>
      </ConexusLightbox>
    );
  }
}
const styles = StyleSheet.create({
  content: {
    flex: 1,
    flexDirection: 'column',
    marginTop: 18,
    alignSelf: 'stretch',
    alignItems: 'stretch',
    padding: 20,
  },

  lightboxFooter: {
    backgroundColor: '#F0FAFF',
    borderTopColor: AppColors.lightBlue,
    borderTopWidth: 1,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },

  list: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'stretch',
  },

  listItem: {
    backgroundColor: AppColors.white,
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.lightBlue,
  },

  litsItemTitleWrapper: {
    flex: 1,
    justifyContent: 'center',
  },

  listItemTitle: {
    ...AppFonts.listItemTitleTouchable,
  },

  listItemIcon: {
    alignSelf: 'flex-end',
  },
});

export default DeviceInfoLightbox;
