export const Strings = {
  NOTIFICATIONS: 'Notifications',
  COMPANY: 'Company',
  TITLE: 'Title',
  E_MAIL: 'E-Mail',
  SUBMIT: 'SUBMIT',
  EDIT: 'EDIT',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  SIGN_IN: 'SIGN IN',
  PHONE_NUMBER: 'Phone Number',
  RECRUITER: 'Recruiter',
  EMAIL_USERNAME: 'Email address',
  PASSWORD: 'Password',
  RECOVER_NOW: 'RECOVER NOW',
  FACILITY: 'FACILITY',
  JOB_CANDIDATE: 'JOB CANDIDATE',
  I_AM: 'I am a...',
  HOW_KNOW: 'How did you hear about us?',
  LOGIN: 'Login',
  SAVE: 'SAVE',
  CREATE_ACCOUNT: 'CREATE ACCOUNT',
  FORGOT_PASSWORD: 'FORGOT PASSWORD ?',
  LOGOUT: 'LOGOUT',
  VALIDATE_FIRST_NAME: 'Please enter first name',
  VALIDATE_LAST_NAME: 'Please enter first last',
  VALIDATE_TITLE: 'Please enter title',
  VALIDATE_PHONE_NO: 'Please enter phone number',
  PROFILE_UPDATED: 'Profile updated Successfully!',
  CHOOSE_PROFILE_PHOTO: 'CHOOSE PROFILE PHOTO',
  REQUEST_ACCOUNT: 'New to Conexus? Request an account now!',
  API_ERROR: 'Something went wrong, try again after sometime',
  EMPTY_EMAIL_USERNAME: 'Please enter email address or username',
  VALID_EMAIL_USERNAME: 'Please enter valid email address or username',
  EMPTY_PASS: 'Please enter password',
  PASS_LENGTH: 'Password length must be equal or greater then 4 digits',
  REGISTERED: 'Registered Successfully',
  MESSAGE_SENT: 'Message sent successfully!',
  FEEDBACK_NOTIFY: 'Feedback submitted successfully',
  INVALID_MSG: 'Invalid message please type a message to send.',
  QUESTIONS_LOADING_ERROR:
    'An error occurred while loading available questions.',
  RECORD_QUESTIONS: 'RECORD YOUR QUESTION',
  ADD_QUESTION: 'ADD QUESTION',
  QUESTIONS_DELETING_ERROR: 'An error occurred while deleting the question.',
  TYPE_FEEDBACK: 'Type your feedback here',
  TYPE_MESSAGE: 'Type your message',
  CAMERA_PERMISSION: 'Camera Permission',
  APP_NEED_CAMERA: 'App needs camera permission',
  STORAGE_PERMISSION: 'External Storage Write Permission',
  WRITE_PERMISSION: 'App needs write permission',
  AUDIO_ERROR: 'An error while playing the selected audio.',
  SEND_MESSAGE_ERROR: 'The message could not be sent. Please try again.',
  FIRST_CONVERSATIONS: 'This is your first conversation with',
  VIDEO_PLAYING_ERROR: 'An error occurred while playing this video.',
  MO_RESPONSE: ' No Responses Available',
  CONTACT_OPTIONS: 'Contact Options',
  NEED_ERROR: 'Not mounted so doing nothing after data loaded.',
  NEED_UNAVAILABLE: 'We are having trouble loading needs. Please try again.',
  IMAGE_ERROR: ' This image cannot be displayed...',
  ADD_TIME: 'Add Time to These Days',
  NEXT: 'Next',
  UNAVAILABLE_SCHEDULING: 'Scheduling not yet available.',
  ENTER_TEXT: 'Please enter the text of your question.',
  CHOOSE_UNIT: 'Please choose a unit.',
  DEFAULT_UNIT_QUESTION: 'Default question for this unit.',
  EDIT_VIRTUAL_INTERVIEW: 'Edit Virtual Interview',
  MAKE_OFFER: 'Make Offer',
  CONVERSATION_LOADING_ERROR:
    'We are having trouble loading your conversations. Please try again.',
  INTERVIEW_QUESTION_LOADING_ERROR:
    'An error occurred while loading the interview questions. Please try again.',
  INTERESTED_CANDIDATE:
    'Are you sure you are not interested in this candidate?',
  UNAVAILABLE_ANSWER_ERROR:
    'The answers for the specified interview questions are currently unavailable.',
  SAVING_RATING_ERROR:
    'An error occurred while saving your rating. Please try again.',
  HARDWARE_ACCESS_ERROR:
    'Permission to access hardware was blocked, please grant manually',
  MESSAGE_CENTER_ERROR:
    'We are having trouble loading your conversations. Please try again.',
  SEND: 'SEND',
  PHOTO_SAVING_ERROR:
    'An unexpected error occurred while saving your profile photo. Please try again.',
  REGISTERED_NOTIFY:
    'Thank you for your request. A Conexus Account Manager will be in touch with you shortly',
};
